[project]
name = "wise-graduate-school-life"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grandalf==0.8",
    "langchain[openai]==0.3.27",
    "langgraph==0.6.6",
    "langgraph-checkpoint-sqlite==2.0.11",
    "langgraph-cli[inmem]==0.4.0",
    "python-dotenv==1.1.1",
    "pydantic>=2.0",
    "streamlit>=1.30.0",
    "mineru[all]>=3.0.8",
    "docling>=2.84.0",
    "marker-pdf",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
