AGENT_LIST = [
    {"name": "Triage Agent", "emoji": "🎯", "desc": "안내 담당"},
    {"name": "Menu Agent", "emoji": "📋", "desc": "메뉴 상담"},
    {"name": "Order Agent", "emoji": "🛒", "desc": "주문 관리"},
    {"name": "Reservation Agent", "emoji": "📅", "desc": "예약 관리"},
    {"name": "Complaint Agent", "emoji": "📢", "desc": "불편 처리"},
]

MENU_DATA = [
    {
        "name": "김치찌개",
        "ingredients": ["김치", "돼지고기", "두부", "대파", "고춧가루"],
        "price": 9000,
        "calories": 380,
        "category": "찌개",
    },
    {
        "name": "된장찌개",
        "ingredients": ["된장", "두부", "감자", "호박", "대파", "고추"],
        "price": 8500,
        "calories": 320,
        "category": "찌개",
    },
    {
        "name": "불고기",
        "ingredients": ["소고기", "양파", "당근", "배", "간장", "참기름"],
        "price": 15000,
        "calories": 450,
        "category": "고기",
    },
    {
        "name": "갈비찜",
        "ingredients": ["소갈비", "무", "당근", "밤", "대추", "간장"],
        "price": 28000,
        "calories": 620,
        "category": "고기",
    },
    {
        "name": "삼겹살",
        "ingredients": ["돼지고기", "마늘", "상추", "쌈장"],
        "price": 16000,
        "calories": 550,
        "category": "고기",
    },
    {
        "name": "비빔밥",
        "ingredients": ["밥", "시금치", "당근", "콩나물", "고추장", "계란"],
        "price": 10000,
        "calories": 480,
        "category": "밥",
    },
    {
        "name": "해물파전",
        "ingredients": ["밀가루", "오징어", "새우", "대파", "계란"],
        "price": 14000,
        "calories": 390,
        "category": "전",
    },
    {
        "name": "잡채",
        "ingredients": ["당면", "시금치", "당근", "버섯", "소고기", "간장"],
        "price": 12000,
        "calories": 350,
        "category": "반찬",
    },
    {
        "name": "냉면",
        "ingredients": ["메밀면", "육수", "소고기", "무", "계란", "겨자"],
        "price": 11000,
        "calories": 430,
        "category": "면",
    },
    {
        "name": "떡볶이",
        "ingredients": ["떡", "어묵", "고추장", "대파", "삶은계란"],
        "price": 7000,
        "calories": 410,
        "category": "분식",
    },
    {
        "name": "순두부찌개",
        "ingredients": ["순두부", "해물", "계란", "대파", "고춧가루"],
        "price": 9500,
        "calories": 290,
        "category": "찌개",
    },
    {
        "name": "제육볶음",
        "ingredients": ["돼지고기", "고추장", "양파", "대파", "고추"],
        "price": 11000,
        "calories": 480,
        "category": "고기",
    },
]

COMMON_ALLERGENS = [
    "땅콩",
    "우유",
    "계란",
    "밀",
    "대두",
    "새우",
    "게",
    "오징어",
    "돼지고기",
    "소고기",
    "복숭아",
    "토마토",
]
